import type { Metadata } from "next";
import type { CSSProperties } from "react";
import "./globals.css";
import { StorefrontProvider } from "@/components/storefront/StorefrontProvider";
import { getPublicStoreSettings } from "@/lib/store-settings-server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const settings = await getPublicStoreSettings();
  const cssVariables = {
    "--primary": settings.primaryColor,
    "--secondary": settings.secondaryColor,
    "--accent": settings.accentColor,
    "--background": settings.backgroundColor,
    "--primary-foreground": getReadableTextColor(settings.primaryColor),
    "--accent-foreground": getReadableTextColor(settings.accentColor),
  } as CSSProperties;

  return (
    <html lang="pt-BR" className="h-full antialiased" style={cssVariables}>
      <body className="min-h-full">
        <StorefrontProvider settings={settings}>{children}</StorefrontProvider>
      </body>
    </html>
  );
}

function getReadableTextColor(color: string) {
  const match = /^#([0-9a-f]{6})$/i.exec(color);
  if (!match) return "#FFFFFF";

  const channels = match[1].match(/.{2}/g);
  if (!channels) return "#FFFFFF";

  const [red, green, blue] = channels.map((channel) => parseInt(channel, 16) / 255);
  const luminance = 0.2126 * red + 0.7152 * green + 0.0722 * blue;
  return luminance > 0.62 ? "#1A1208" : "#FFFFFF";
}
